// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable no-irregular-whitespace, @typescript-eslint/ban-types -- auto-generated by typesafe-i18n */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	FILE_POSITION: {
		/**
		 * 文​件​位​置
		 */
		LABEL: string
		/**
		 * 指​定​文​件​要​保​存​的​位​置
		 */
		DESC: string
		/**
		 * 请​输​入​文​件​路​径
		 */
		PATH_INPUT_PLACEHOLDER: string
		TYPE: {
			/**
			 * 仓​库​的​根​目​录
			 */
			ROOT: string
			/**
			 * 当​前​文​件​所​在​目​录
			 */
			CURRENT: string
			/**
			 * 当​前​文​件​所​在​子​目​录
			 */
			SUBFOLDER: string
			/**
			 * 自​定​义​目​录​路​径
			 */
			CUSTOM: string
		}
	}
	SCOPE: {
		/**
		 * 适​用​范​围
		 */
		LABEL: string
		/**
		 * 该​规​则​生​效​的​范​围
		 */
		DESC: string
		TYPE: {
			/**
			 * 全​部
			 */
			ALL: string
			/**
			 * 指​定​文​件​类​型
			 */
			SPECIFIC_EXTENSION: string
			/**
			 * 指​定​目​录
			 */
			SPECIFIC_FOLDER: string
			/**
			 * 标​签
			 */
			TAG_OPS: string
			/**
			 * 自​定​义
			 */
			CUSTOM: string
		}
		/**
		 * 请​输​入​标​签​,​ ​按​下​回​车​或​空​格​确​定
		 */
		TAG_VALUE_INPUT_PLACEHOLDER: string
		/**
		 * 请​输​入​文​件​类​型​的​后​缀​，​比​如​ ​p​n​g​.​ ​按​下​回​车​或​空​格​确​定
		 */
		EXTENSION_VALUE_INPUT_PLACEHOLDER: string
		/**
		 * 请​填​写​目​录​路​径​，​按​下​回​车​确​定
		 */
		SPECIFIC_FOLDER_INPUT_PLACEHOLDER: string
	}
	FILE_NAME_FORMAT: {
		/**
		 * 文​件​名​格​式​化
		 */
		LABEL: string
		/**
		 * 自​动​将​文​件​名​称​转​为​指​定​的​格​式
		 */
		DESC: string
		/**
		 * 自​动​将​文​件​名​称​转​为​指​定​的​格​式​。
		 */
		DATETIME_DESC: string
		/**
		 * 查​看​ ​L​u​x​o​n​ ​格​式​文​档
		 */
		DATETIME_DESC_DOC: string
		/**
		 * 示​例
		 */
		EXAMPLE: string
		/**
		 * 默​认​为​ ​y​y​y​y​M​M​d​d​H​H​m​m​s​s
		 */
		DATETIME_INPUT_PLACEHOLDER: string
		/**
		 * 请​输​入​自​定​义​格​式
		 */
		CUSTOM_INPUT_PLACEHOLDER: string
		/**
		 * 你​可​以​使​用​ ​{​a​t​t​a​c​h​m​e​n​t​N​a​m​e​}​,​ ​{​n​o​t​e​n​a​m​e​}​ ​或​ ​{​u​u​i​d​}​ ​等​等
		 * @param {unknown} attachmentName
		 * @param {unknown} notename
		 * @param {unknown} uuid
		 */
		CUSTOM_DESC: RequiredParams<'attachmentName' | 'notename' | 'uuid'>
		TYPE: {
			/**
			 * 当​前​时​间
			 */
			DATETIME: string
			/**
			 * 全​局​唯​一​标​识​符​（​U​U​I​D​）
			 */
			UUID: string
			/**
			 * 原​始​文​件​名
			 */
			ORIGINAL: string
			/**
			 * 自​定​义​格​式
			 */
			CUSTOM: string
		}
	}
	SETTING: {
		/**
		 * 删​除
		 */
		RULE_DELETE_BUTTON_TEXT: string
		/**
		 * 添​加
		 */
		RULE_ADD_BUTTON_TEXT: string
		/**
		 * 向​上​移​动
		 */
		MOVE_UP_TOOLTIP: string
		/**
		 * 向​下​移​动
		 */
		MOVE_DOWN_TOOLTIP: string
		/**
		 * 包​含​以​下​全​部
		 */
		OPERATOR_CONTAINS_ALL: string
		/**
		 * 包​含​任​意​一​个
		 */
		OPERATOR_CONTAINS_ANY: string
	}
	ATTACHMENTS: {
		/**
		 * 插​入​选​中​的​附​件
		 */
		INSERT_SELECTED_ATTACHMENTS: string
		/**
		 * 附​件​加​载​中​.​.​.
		 */
		LOADING: string
		/**
		 * 没​有​找​到​附​件
		 */
		EMPTY_TITLE: string
		/**
		 * 试​着​调​整​筛​选​条​件​，​或​先​向​仓​库​中​添​加​附​件​。
		 */
		EMPTY_DESC: string
		/**
		 * 图​片​（​全​部​）
		 */
		FILTER_IMAGES_ALL: string
		/**
		 * 按​名​称​搜​索
		 */
		SEARCH_PLACEHOLDER: string
		/**
		 * 仅​未​引​用
		 */
		ONLY_UNUSED: string
		/**
		 * 无​法​预​览​该​文​件​类​型
		 */
		PREVIEW_UNSUPPORTED: string
		/**
		 * 上​一​页
		 */
		PAGINATION_PREV: string
		/**
		 * 下​一​页
		 */
		PAGINATION_NEXT: string
		/**
		 * 关​闭
		 */
		MODAL_CLOSE: string
	}
	NOTICES: {
		/**
		 * A​t​t​a​c​h​m​e​n​t​ ​P​r​o​:​ ​附​件​保​存​失​败
		 */
		SAVE_FAILED: string
	}
	COMMAND: {
		/**
		 * 打​开​附​件​库
		 */
		SHOW_ATTACHMENTS: string
		/**
		 * 从​附​件​库​中​插​入
		 */
		CONTEXT_MENU_INSERT_ATTACHMENTS: string
	}
}

export type TranslationFunctions = {
	FILE_POSITION: {
		/**
		 * 文件位置
		 */
		LABEL: () => LocalizedString
		/**
		 * 指定文件要保存的位置
		 */
		DESC: () => LocalizedString
		/**
		 * 请输入文件路径
		 */
		PATH_INPUT_PLACEHOLDER: () => LocalizedString
		TYPE: {
			/**
			 * 仓库的根目录
			 */
			ROOT: () => LocalizedString
			/**
			 * 当前文件所在目录
			 */
			CURRENT: () => LocalizedString
			/**
			 * 当前文件所在子目录
			 */
			SUBFOLDER: () => LocalizedString
			/**
			 * 自定义目录路径
			 */
			CUSTOM: () => LocalizedString
		}
	}
	SCOPE: {
		/**
		 * 适用范围
		 */
		LABEL: () => LocalizedString
		/**
		 * 该规则生效的范围
		 */
		DESC: () => LocalizedString
		TYPE: {
			/**
			 * 全部
			 */
			ALL: () => LocalizedString
			/**
			 * 指定文件类型
			 */
			SPECIFIC_EXTENSION: () => LocalizedString
			/**
			 * 指定目录
			 */
			SPECIFIC_FOLDER: () => LocalizedString
			/**
			 * 标签
			 */
			TAG_OPS: () => LocalizedString
			/**
			 * 自定义
			 */
			CUSTOM: () => LocalizedString
		}
		/**
		 * 请输入标签, 按下回车或空格确定
		 */
		TAG_VALUE_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * 请输入文件类型的后缀，比如 png. 按下回车或空格确定
		 */
		EXTENSION_VALUE_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * 请填写目录路径，按下回车确定
		 */
		SPECIFIC_FOLDER_INPUT_PLACEHOLDER: () => LocalizedString
	}
	FILE_NAME_FORMAT: {
		/**
		 * 文件名格式化
		 */
		LABEL: () => LocalizedString
		/**
		 * 自动将文件名称转为指定的格式
		 */
		DESC: () => LocalizedString
		/**
		 * 自动将文件名称转为指定的格式。
		 */
		DATETIME_DESC: () => LocalizedString
		/**
		 * 查看 Luxon 格式文档
		 */
		DATETIME_DESC_DOC: () => LocalizedString
		/**
		 * 示例
		 */
		EXAMPLE: () => LocalizedString
		/**
		 * 默认为 yyyyMMddHHmmss
		 */
		DATETIME_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * 请输入自定义格式
		 */
		CUSTOM_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * 你可以使用 {attachmentName}, {notename} 或 {uuid} 等等
		 */
		CUSTOM_DESC: (arg: { attachmentName: unknown, notename: unknown, uuid: unknown }) => LocalizedString
		TYPE: {
			/**
			 * 当前时间
			 */
			DATETIME: () => LocalizedString
			/**
			 * 全局唯一标识符（UUID）
			 */
			UUID: () => LocalizedString
			/**
			 * 原始文件名
			 */
			ORIGINAL: () => LocalizedString
			/**
			 * 自定义格式
			 */
			CUSTOM: () => LocalizedString
		}
	}
	SETTING: {
		/**
		 * 删除
		 */
		RULE_DELETE_BUTTON_TEXT: () => LocalizedString
		/**
		 * 添加
		 */
		RULE_ADD_BUTTON_TEXT: () => LocalizedString
		/**
		 * 向上移动
		 */
		MOVE_UP_TOOLTIP: () => LocalizedString
		/**
		 * 向下移动
		 */
		MOVE_DOWN_TOOLTIP: () => LocalizedString
		/**
		 * 包含以下全部
		 */
		OPERATOR_CONTAINS_ALL: () => LocalizedString
		/**
		 * 包含任意一个
		 */
		OPERATOR_CONTAINS_ANY: () => LocalizedString
	}
	ATTACHMENTS: {
		/**
		 * 插入选中的附件
		 */
		INSERT_SELECTED_ATTACHMENTS: () => LocalizedString
		/**
		 * 附件加载中...
		 */
		LOADING: () => LocalizedString
		/**
		 * 没有找到附件
		 */
		EMPTY_TITLE: () => LocalizedString
		/**
		 * 试着调整筛选条件，或先向仓库中添加附件。
		 */
		EMPTY_DESC: () => LocalizedString
		/**
		 * 图片（全部）
		 */
		FILTER_IMAGES_ALL: () => LocalizedString
		/**
		 * 按名称搜索
		 */
		SEARCH_PLACEHOLDER: () => LocalizedString
		/**
		 * 仅未引用
		 */
		ONLY_UNUSED: () => LocalizedString
		/**
		 * 无法预览该文件类型
		 */
		PREVIEW_UNSUPPORTED: () => LocalizedString
		/**
		 * 上一页
		 */
		PAGINATION_PREV: () => LocalizedString
		/**
		 * 下一页
		 */
		PAGINATION_NEXT: () => LocalizedString
		/**
		 * 关闭
		 */
		MODAL_CLOSE: () => LocalizedString
	}
	NOTICES: {
		/**
		 * Attachment Pro: 附件保存失败
		 */
		SAVE_FAILED: () => LocalizedString
	}
	COMMAND: {
		/**
		 * 打开附件库
		 */
		SHOW_ATTACHMENTS: () => LocalizedString
		/**
		 * 从附件库中插入
		 */
		CONTEXT_MENU_INSERT_ATTACHMENTS: () => LocalizedString
	}
}

export type Formatters = {}
